### ISSUE TITLE
Add resolveTypeReference helper

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1202]
Implementation issue for https://github.com/microsoft/cadl/issues/1065

- [x] Create new checker function `resolveTypeReference(string fullyQualifiedName): Type`
  - input should include fully qualified type id `foo.bar.baz` and may include metainfo syntax (e.g. `model.propertyName::type`)
- [x] Add helper function `resolveTypeReference` in `Program`
- [x] Add tests
- [x] Add documentation to emitter developer docs

validate:
- [ ] cannot instantiate a template that is not already created

**Comment by markcowl** [comment]
est: 8
