### ISSUE TITLE
Implementation: Simplify versioned dependencies

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#1356]
Implementation issue for: #857

Change version enumeration to carry version dependency information.

- [x] Add new decorator `@useDependency`
  - Takes one or more dependency versions as parameter (enum member references)
  - Can target an enum member, or a namespace
    - enum member: Validate that enum containing decoration is mentioned in `@versioned` decorator
    - namespace: validate that namespace is not decorated with `@versioned`
- [x] Deprecate the `@versionedDependency` decorator
- [x] Update version projection logic to use the `@useDependency` decorator
