### ISSUE TITLE
Tracking: Implement emitter API

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#191]
Per #41, implement the emitters api for all of our emitters (oss and Azure)
 - [ ] Determine how to do the validations currently in OnBuild in emitters
 - [x] Determine how to update the language server to support validation in emitters
 - [x] Determine mechanism for performing emitter validations in the language server for non-imported emitters
   - [x] Do we use configuration to determine which extension we call OnValidate for
 - [ ] Add size estimate for remaining work after this PR
   - [ ] private repo emitters (PR)

**Comment by timotheeguerin** [comment]
I updated Friday the emitter PR to have the language server load the cadl config of the project and be able to load the emitter. This solve the main part of this problem.

If we want to think about separating the validation from the emitting then I think this is now a completely independent task and might not even make sense for some emitter:

`onValidate` would only get called if you import the library(so if you want to use some decorators from it or the validation it does)

**Comment by markcowl** [comment]
- [ ] for emitters, OnBuild -> OnEmit
- [ ] config for public (openapi3)/private(cadl-autorest) repo default openapi emitter // no work, I think
- [ ] ensure cadl-rpaas-controller.OnEmit is called during compile // no work, I think
- [ ] cadl emit generate config file
- [ ] document the configuration file
