### ISSUE TITLE
Write a tutorial on developing an emitter

### ISSUE THREAD

**Issue by markcowl** [microsoft/cadl#549]
Write an emitter tutorial, including:
- [ ] Providing command line emitter options
- [ ] Implementing OnEmit
  - [ ] Using projections
  - [ ] Diagnostics and logging
  - [ ] Using the host methods for interacting with the fie system

**Comment by markcowl** [comment]
Completed
