### ISSUE TITLE
Add @client and @clientParameter and @operationGroup decorators

### ISSUE THREAD

**Issue by daviwil** [microsoft/cadl#778]
To describe generated code clients for a service, it will be necessary to reuse elements from the original Cadl service specification to shape a client by forming explicit groupings of operations and models.

**Tasks**

- [ ] Create a decorator for client grouping that can be applied on the namespace, interface, and operation level.  
  - Use an enumeration over the names of defined clients
  - The decorator references a client enum value to associate the operations in the decorated item with a particular client
- [ ] Create a decorator that can be applied to a root namespace that specifies a client
  - Decorator defines construction parameters
  - Need to determine the interaction with `@server` decorators
    - Perhaps reuse server parameter models
    - Perhaps make Client a model template that can be decorated with @server parameters

- [ ] Model a few data plane services and revisit

This is an implementation issue to solve the following design issues:

- https://github.com/microsoft/cadl/issues/656
- https://github.com/microsoft/cadl/issues/664
- https://github.com/microsoft/cadl/issues/678

Johan's original example:

```
/***
  Example service that the client libraries want to break down
  into three clients, admin, text inferrence and image inferrence.
  The image inferrence client is bound to a specific model id (and
  thus should have a imageId constructor parameter).
***/
import "@cadl-lang/rest";
using Cadl.Http;
interface ExampleService {
  @post @route("trainModel") op trainModel(modelId: string): string;
  @post @route("inferText") op inferText(): void;
  @post @route("inferImage") op inferImage(modelId: string): void;
}
/* --------------- Separate file for client library generation ------------ */
// The @client decorator indicates that this interface should be, well, a client
@client    
interface ExampleAdminClient {
  trainModel is ExampleService.trainModel;
  
  // We even provide an operation template to let people specify
  // subclient "getters"
  getImageInferrenceClient is Azure.Sdk.Subclient<ImageInferrenceClient>;
}
@client
interface TextInferrenceClient {
  inferText is ExampleService.inferText;
}
// Rather than annotating all parameters for all methods, 
// you can specify the parameters to the client 
@client({ clientParameters: { modelId: string }})
interface ImageInferrenceClient {
  inferImage is ExampleService.inferImage;
}
```

**Comment by markcowl** [comment]
@daviwil @johanste verifying which sprint this should go in, and if these should be split out

**Comment by markcowl** [comment]
estimate: 8
